#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S3,     gyroSensor,     sensorNone)
#pragma config(Sensor, S4,     sonarSensor,    sensorNone)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//our calculated threshold from previous programme
	int threshold=49;

	//while colorSensor is greater than threshold, move forward until it reaches a dark area thats 1cm thick
	while(true)
	{
			//if the colorSensor is greater than the threshold, move forward until statement is false
			if(SensorValue(colorSensor)>threshold)
			{
				setMotorSpeed(motorC, 50);
		 		setMotorSpeed(motorB, 50);
			}
			//when statement is false, stop the robot from moving
			else
			{
				setMotorSpeed(motorC, 0);

				setMotorSpeed(motorB, 0);
			}

	}

}
