#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S3,     gyroSensor,     sensorNone)
#pragma config(Sensor, S4,     sonarSensor,    sensorNone)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//variables for light, dark, sum and threshold values
	int lightValue;
	int darkValue;
	int sumValue;
	int thresholdValue;


	//while the touchSensor is not pressed, gets the dark value and prints it
	while (SensorValue(touchSensor)==0)
	{

		darkValue=SensorValue(colorSensor);
		wait1Msec(1000);

		displayCenteredTextLine(3,"The dark value is \n %d", darkValue);
		wait1Msec(1000);
		}


		//while the touchSensor is pressed, gets the light value and prints it
	while (SensorValue(touchSensor)==1)
	{
		displayCenteredTextLine(3,"Press the touch \n sensor to read \n the light value");
		wait1Msec(1000);

		lightValue=SensorValue(colorSensor);
		wait1Msec(1000);

		displayCenteredTextLine(3,"The light value is \n %d", lightValue);
		wait1Msec(1000);

		//calculating threshold
		sumValue = lightValue + darkValue;

		thresholdValue = sumValue/2;

		displayCenteredTextLine(3,"The threshold value \n is  %d", thresholdValue);
		wait1Msec(3000);
	}

}
