#pragma config(Sensor, S1, touchSensor, sensorEV3_Touch)
#pragma config(Sensor, S2, gyroSensor, sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3, colorSensor, sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4, sonarSensor, sensorEV3_Ultrasonic)
#pragma config(Motor, motorA, armMotor, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorB, leftMotor, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorC, rightMotor, tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define circumfrance 17.27

//function drive() calculates full rotation by multiplying 360 by the distance divided by the circumfrance
void drive(long nMotorRatio, long dist, long power)
{
	float rotations = 360 * (dist/circumfrance);

	resetMotorEncoder(motorC);
	resetMotorEncoder(motorB);

	setMotorSyncEncoder(motorC, motorB, nMotorRatio, rotations, power);

	waitUntilMotorStop(motorB);
}

//function getdistance() allows user to choose distance based off buttonpressed
int getDistance(int distance)
{

	while (getButtonPress(buttonEnter) == 0 )
	{

		displayCenteredBigTextLine(4,"Distance = %dcm", distance);
		//if user presses buttonup, drive 10cm
		if (getButtonPress(buttonUp))
		{
			distance = 10;
			displayCenteredBigTextLine(4,"Distance = %dcm", distance);
			drive(0,10,50);
		}
		//else if user presses buttondown drive 40cm
		else if (getButtonPress(buttonDown))
		{
			distance = 40;
			displayCenteredBigTextLine(4,"Distance = %dcm", distance);
			drive(0,40,50);
		}
		//else if user presses buttonleft drive 60cm
		else if (getButtonPress(buttonLeft))
		{
			distance = 60;
			displayCenteredBigTextLine(4,"Distance = %dcm", distance);
			drive(0,60,50);
		}
		//else if user presses buttonright drive 80cm
		else if (getButtonPress(buttonRight))
		{
			distance = 80;
			displayCenteredBigTextLine(4,"Distance = %dcm", distance);
			drive(0,80,50);
		}
		sleep(20);
	}
	return distance;
}


task main()
{

	int distance = 0;


	displayCenteredTextLine(1, "Button pressed:");
	displayCenteredBigTextLine(6,"Final Distance = %dcm", getDistance(distance));
	sleep(2000);

}
