#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          gyroMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int k;
//this is set to 0 because 50 is middle
k = 50; 
//will loop forever
while(true)
{
  // displays what the angle is
   displayCenteredTextLine(3, "angle %d", getGyroDegrees(S3));

  //motor speed set based on gyro degrees
  setMotorSpeed(leftMotor, k+(getGyroDegrees(S3)));
  setMotorSpeed(rightMotor, k+(getGyroDegrees(S3)));

  //If the gyro sensor is turning left
  //move the robot to the right
  if (getGyroDegrees(S3) >= 50)
   {
      setMotorSpeed(gyroMotor, -5);
    }
    else if (getGyroDegrees(S3) <= -50)
    {
      setMotorSpeed(gyroMotor, 5);
    }
}
}
