#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          gyroMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int p;
  p = 50; // since 50 is the middle, it is set to 0
//Keep looping forever
while(true)
{


  // displays what the current angle is

   displayCenteredTextLine(2, "Angle %d", getGyroDegrees(S3));



  // sets the motor speeds based on what the gyro degrees are

  setMotorSpeed(leftMotor, p+(getGyroDegrees(S3)));

  setMotorSpeed(rightMotor, p+(getGyroDegrees(S3)));



		//If the gyro sensor is turning to the left,
		//countersteer the robot to the right
    if (getGyroDegrees(S3) >= 50)

   {

      setMotorSpeed(gyroMotor, -5);

    }



    else if (getGyroDegrees(S3) <= -50)

    {

      setMotorSpeed(gyroMotor, 5);

    }
}
}
