#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn90();
void reset();
task main()
{

	while(SensorValue(touchSensor)== 0)
	{
		setMotorSpeed (motorB, 50;
		setMotorSpeed (motorC, 50;
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	wait1Msec(500);

	//this is to move slightly back
	setMotorSpeed(motorB, -30);
	setMotorSpeed(motorC, -30);
	wait1Msec(500);

	reset();
	turn90();


	while(SensorValue(sonarSensor)>10)
	{
		setMotorSpeed (motorB, 50;
		setMotorSpeed (motorC, 50;

	}
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	wait1Msec(500);

	setMotorSpeed(motorB, -30);
	setMotorSpeed(motorC, -30);
	wait1Msec(500);
	reset();
	turn90();

	while(SensorValue(touchSensor)== 0)
	{
		setMotorSpeed (motorB, 50;
		setMotorSpeed (motorC, 50;
	}

	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	wait1Msec(500);

	//this is to move slightly back
	setMotorSpeed(motorB, -30);
	setMotorSpeed(motorC, -30);
	wait1Msec(500);
	reset();
	turn90();

	nMotorEncoder (motorB) =  0;


	// this is for the robot to move forward 30 centimeters
	while(nMotorEncoder(motorB)<(360*30/17.27))
	{
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
	}


}


//using the gyro to get an accurate 90 degree turn
void turn90()
{

	resetGyro(gyroSensor);

	while(SensorValue(gyroSensor) < 89)
	{
		setMotorSync(leftMotor, rightMotor, 50,100);
  }
}

//this function resets the motors to get an accurate turn
void reset()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
}
